import { useEffect, type ReactNode } from "react";
import { createPortal } from "react-dom";
import type { AIProcessTraceEvent } from "../../types";
import { useI18n } from "../../lib/i18n";

export default function ProcessTrace({ events }: { events?: AIProcessTraceEvent[] }) {
  const { tr } = useI18n();
  if (!events?.length) return <p className="text-xs text-slate-400">{tr("Chưa có nhật ký. Hãy tạo lại kết quả.", "No log yet. Regenerate the result.")}</p>;
  return <div className="ai-log-timeline overflow-hidden rounded-xl border border-slate-200">{events.map((event, index) => <article key={event.id} className="ai-log-event border-b border-slate-200 p-3.5 last:border-b-0"><div className="flex items-start gap-3"><span className={`ai-log-step is-${event.status} flex h-6 w-6 shrink-0 items-center justify-center rounded-full border text-[10px] font-semibold`}>{index + 1}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-x-2 gap-y-1"><h4 className="text-[11px] font-medium text-slate-800">{event.title}</h4><span className="rounded-full border border-slate-200 px-2 py-0.5 text-[8px] font-medium uppercase tracking-wider text-slate-400">{event.stage}</span></div><p className="mt-1.5 whitespace-pre-wrap text-[10px] leading-relaxed text-slate-500">{event.detail}</p>{event.facts && <div className="mt-2 flex flex-wrap gap-1.5">{Object.entries(event.facts).map(([key, value]) => <span key={key} className="ai-log-fact rounded-md border border-slate-200 px-2 py-1 text-[9px] text-slate-500"><b className="font-medium text-slate-700">{key}:</b> {String(value ?? "n/a")}</span>)}</div>}{(event.sources?.length ?? 0) > 0 && <div className="mt-2 flex flex-wrap gap-1.5">{event.sources?.map((url, sourceIndex) => <a key={`${url}-${sourceIndex}`} href={url} target="_blank" rel="noreferrer" className="ai-log-source rounded-md px-2 py-1 text-[9px] font-medium">Source {sourceIndex + 1}</a>)}</div>}</div></div></article>)}</div>;
}

export function ProcessTraceModal({ title, events, onClose, children }: { title: string; events?: AIProcessTraceEvent[]; onClose: () => void; children?: ReactNode }) {
  const { tr } = useI18n();
  useEffect(() => { const close = (event: KeyboardEvent) => event.key === "Escape" && onClose(); window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [onClose]);
  return createPortal(<div className="fixed inset-0 z-[110] flex items-center justify-center bg-slate-950/30 p-3 backdrop-blur-sm sm:p-6" onMouseDown={event => event.target === event.currentTarget && onClose()} role="dialog" aria-modal="true" aria-label={title}><div className="writer-light contents"><div className="ai-log-modal flex max-h-[92dvh] w-full max-w-4xl flex-col overflow-hidden rounded-2xl border border-slate-200 bg-white"><header className="flex items-start justify-between gap-3 border-b border-slate-100 px-4 py-4 sm:px-5"><div className="min-w-0"><p className="text-[9px] font-medium uppercase tracking-wider text-slate-400">{tr("Nhật ký AI", "AI log")}</p><h3 className="mt-1 truncate text-sm font-medium text-slate-800">{title}</h3><p className="mt-1 text-[10px] text-slate-500">{tr("Hành động và dữ liệu có thể kiểm chứng.", "Verifiable actions and supporting data.")}</p></div><button onClick={onClose} className="ai-log-close flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-lg text-slate-500" aria-label={tr("Đóng", "Close")}>×</button></header><div className="ai-log-content flex-1 space-y-5 overflow-y-auto p-4 sm:p-5"><ProcessTrace events={events} />{children}</div></div></div></div>, document.body);
}
