import { BookOpenCheck, ChevronDown, Inbox, LayoutGrid, PanelLeftClose, PanelLeftOpen, Search, Settings, Trash2 } from "lucide-react"
import { useEffect, useState } from "react"
import BrandMark from "./BrandMark"
interface Props { onOpenSettings: () => void; onNewPackage: () => void; onOpenDiscovery: () => void }
export default function EbSidebar({ onOpenSettings, onNewPackage, onOpenDiscovery }: Props) {
  const [collapsed, setCollapsed] = useState(false)
  const [starred, setStarred] = useState<Array<{ id: string; title: string; color: string }>>([])
  const [counts, setCounts] = useState({ discovery: 0, library: 0 })
  const hidden = collapsed ? "hidden" : ""
  useEffect(() => { const update = (event: Event) => setStarred((event as CustomEvent<Array<{ id: string; title: string; color: string }>>).detail); window.addEventListener("writer:eb-items", update); return () => window.removeEventListener("writer:eb-items", update) }, [])
  useEffect(() => { const update = (event: Event) => setCounts((event as CustomEvent<{ discovery: number; library: number }>).detail); window.addEventListener("writer:eb-counts", update); return () => window.removeEventListener("writer:eb-counts", update) }, [])
  const open = (view: "new" | "discovery" | "library") => { window.dispatchEvent(new CustomEvent("writer:eb-open", { detail: view })); if (view === "new") onNewPackage(); if (view === "discovery") onOpenDiscovery() }
  return <aside className={`eb-sidebar hidden h-full shrink-0 flex-col justify-between rounded-2xl border border-slate-200/80 bg-slate-50 shadow-sm transition-[width,padding] duration-250 md:flex ${collapsed ? "w-16 p-2" : "w-64 p-3"}`}>
    <div className="flex flex-col gap-4 overflow-hidden"><div className="flex items-center justify-between rounded-lg px-2 py-1.5 hover:bg-slate-200/60"><button onClick={onNewPackage} className="flex min-w-0 items-center gap-2"><BrandMark className="h-5 w-5"/><span className={`truncate text-xs font-semibold text-slate-800 ${hidden}`}>Writer Studio</span><ChevronDown className={`h-4 w-4 shrink-0 text-slate-400 ${hidden}`}/></button><button onClick={() => setCollapsed(value => !value)} className="rounded p-1 text-slate-400 hover:bg-slate-300/50 hover:text-slate-600" aria-label="Toggle sidebar">{collapsed ? <PanelLeftOpen className="h-4 w-4"/> : <PanelLeftClose className="h-4 w-4"/>}</button></div>
      <nav className="space-y-0.5"><SideButton icon={LayoutGrid} label="New activity" active collapsed={collapsed} onClick={() => open("new")}/><SideButton icon={Inbox} label="Discovery" collapsed={collapsed} count={counts.discovery} onClick={() => open("discovery")}/><SideButton icon={BookOpenCheck} label="Library Article" collapsed={collapsed} count={counts.library} onClick={() => open("library")}/></nav>
      <SectionLabel label="Started packages" hidden={hidden}/><div className="space-y-0.5">{starred.length ? starred.map(item => <Star key={item.id} {...item} hidden={hidden}/>) : <p className={`px-2.5 py-1 text-[10px] text-slate-400 ${hidden}`}>No packages yet</p>}</div>
    </div>
    <div className="flex items-center justify-between border-t border-slate-200 pt-2 text-slate-500"><button className="rounded-lg p-1.5 hover:bg-slate-200/60" aria-label="Search"><Search className="h-4 w-4"/></button><button onClick={onOpenSettings} className="rounded-lg p-1.5 hover:bg-slate-200/60" aria-label="Settings"><Settings className="h-4 w-4"/></button></div>
  </aside>
}
function SideButton({ icon: Icon, label, active, collapsed, count, onClick }: { icon: typeof LayoutGrid; label: string; active?: boolean; collapsed: boolean; count?: number; onClick?: () => void }) { return <button onClick={onClick} title={collapsed ? label : undefined} className={`flex h-8 w-full items-center gap-2.5 rounded-lg px-2.5 text-left text-xs font-medium ${active ? "bg-slate-200/70 text-slate-900 font-semibold" : "text-slate-600 hover:bg-slate-200/50"} ${collapsed ? "justify-center px-0" : ""}`}><Icon className="h-4 w-4 shrink-0 text-slate-500"/><span className={collapsed ? "hidden" : "truncate"}>{label}</span>{count !== undefined && <span className={`ml-auto rounded-md bg-slate-200 px-1.5 py-0.5 text-[10px] font-bold text-slate-600 ${collapsed ? "hidden" : ""}`}>{count}</span>}</button> }
function SectionLabel({ label, hidden }: { label: string; hidden: string }) { return <div className={`flex items-center justify-between px-2.5 pt-2 text-[10px] font-semibold uppercase tracking-wider text-slate-400 ${hidden}`}><span>{label}</span><ChevronDown className="h-3.5 w-3.5"/></div> }
function Star({ id, title, color, hidden }: { id: string; title: string; color: string; hidden: string }) { return <div className="group flex h-7 w-full items-center gap-2 rounded-lg px-2.5 text-xs font-medium text-slate-600 hover:bg-slate-200/50"><span className={`h-2 w-2 shrink-0 rounded-full ${color}`}/><span className={`min-w-0 flex-1 truncate ${hidden}`}>{title}</span><button onClick={() => window.dispatchEvent(new CustomEvent("writer:eb-delete", { detail: id }))} title="Delete item" aria-label={`Delete ${title}`} className={`grid h-5 w-5 place-items-center rounded text-slate-400 hover:bg-red-50 hover:text-red-600 ${hidden} group-hover:grid`}><Trash2 className="h-3 w-3"/></button></div> }
