import { BookOpenCheck, ChevronDown, FileText, Inbox, LayoutGrid, PanelLeftClose, PanelLeftOpen, Search, Settings, Trash2, X } from "lucide-react"
import { useEffect, useState } from "react"
import BrandMark from "./BrandMark"
interface Props { onOpenSettings: () => void; onNewPackage: () => void; onOpenDiscovery: () => void }
export default function EbSidebar({ onOpenSettings, onNewPackage, onOpenDiscovery }: Props) {
  const [collapsed, setCollapsed] = useState(false)
  const [starred, setStarred] = useState<Array<{ id: string; packageId?: string; title: string; color: string; gate: string; channel?: string }>>([])
  const [counts, setCounts] = useState({ discovery: 0, library: 0 })
  const [searchOpen, setSearchOpen] = useState(false)
  const [query, setQuery] = useState("")
  const [mobilePackagesOpen, setMobilePackagesOpen] = useState(false)
  const hidden = collapsed ? "hidden" : ""
  useEffect(() => { const update = (event: Event) => setStarred((event as CustomEvent<Array<{ id: string; packageId?: string; title: string; color: string; gate: string; channel?: string }>>).detail); window.addEventListener("writer:eb-items", update); return () => window.removeEventListener("writer:eb-items", update) }, [])
  useEffect(() => { const update = (event: Event) => setCounts((event as CustomEvent<{ discovery: number; library: number }>).detail); window.addEventListener("writer:eb-counts", update); return () => window.removeEventListener("writer:eb-counts", update) }, [])
  const open = (view: "new" | "discovery" | "library") => { window.dispatchEvent(new CustomEvent("writer:eb-open", { detail: view })); if (view === "new") onNewPackage(); if (view === "discovery") onOpenDiscovery() }
  const activeItems = starred.filter(item => item.gate !== "review" && item.gate !== "article")
  const reviewItems = starred.filter(item => item.gate === "review")
  // A fab.careers package remains a website article after it progresses to
  // channel review. Keep one representative entry here while Final review
  // below continues to expose each individual channel action.
  const websiteItems = starred.filter(item => item.gate === "article" || item.gate === "review").filter((item, index, list) => list.findIndex(candidate => (candidate.packageId ?? candidate.id) === (item.packageId ?? item.id)) === index)
  const results = starred.filter(item => item.title.toLowerCase().includes(query.trim().toLowerCase()))
  return <><nav className="flex shrink-0 items-center justify-around rounded-2xl border border-slate-200/80 bg-slate-50 p-1.5 shadow-sm md:hidden"><MobileButton icon={LayoutGrid} label="New" onClick={() => open("new")}/><MobileButton icon={Inbox} label="Discovery" count={counts.discovery} onClick={() => open("discovery")}/><MobileButton icon={FileText} label="Packages" onClick={() => setMobilePackagesOpen(true)}/><MobileButton icon={BookOpenCheck} label="Library" count={counts.library} onClick={() => open("library")}/><MobileButton icon={Settings} label="Settings" onClick={onOpenSettings}/></nav><aside className={`eb-sidebar hidden h-full shrink-0 flex-col justify-between rounded-2xl border border-slate-200/80 bg-slate-50 shadow-sm transition-[width,padding] duration-250 md:flex ${collapsed ? "w-16 p-2" : "w-64 p-3"}`}>
    <div className="flex flex-col gap-4 overflow-hidden"><div className="flex items-center justify-between rounded-lg px-2 py-1.5 hover:bg-slate-200/60"><button onClick={onNewPackage} className="flex min-w-0 items-center gap-2"><BrandMark className="h-5 w-5"/><span className={`truncate text-xs font-semibold text-slate-800 ${hidden}`}>Writer Studio</span><ChevronDown className={`h-4 w-4 shrink-0 text-slate-400 ${hidden}`}/></button><button onClick={() => setCollapsed(value => !value)} className="rounded p-1 text-slate-400 hover:bg-slate-300/50 hover:text-slate-600" aria-label="Toggle sidebar">{collapsed ? <PanelLeftOpen className="h-4 w-4"/> : <PanelLeftClose className="h-4 w-4"/>}</button></div>
      <nav className="space-y-0.5"><SideButton icon={LayoutGrid} label="New activity" active collapsed={collapsed} onClick={() => open("new")}/><SideButton icon={Inbox} label="Discovery" collapsed={collapsed} count={counts.discovery} onClick={() => open("discovery")}/><SideButton icon={BookOpenCheck} label="Library Article" collapsed={collapsed} count={counts.library} onClick={() => open("library")}/></nav>
      <SectionLabel label="Started packages" hidden={hidden}/><StartedPackageGroups activeItems={activeItems} websiteItems={websiteItems} reviewItems={reviewItems} hidden={hidden}/>
    </div>
    <div className="flex items-center justify-between border-t border-slate-200 pt-2 text-slate-500"><button onClick={() => { setSearchOpen(true); setQuery("") }} className="rounded-lg p-1.5 hover:bg-slate-200/60" aria-label="Search"><Search className="h-4 w-4"/></button><button onClick={onOpenSettings} className="rounded-lg p-1.5 hover:bg-slate-200/60" aria-label="Settings"><Settings className="h-4 w-4"/></button></div>
    {searchOpen && <div onClick={event => { if (event.target === event.currentTarget) setSearchOpen(false) }} className="fixed inset-0 z-[70] flex items-start justify-center bg-slate-950/25 p-4 pt-24 backdrop-blur-[1px]"><div className="w-full max-w-lg rounded-2xl border border-slate-200 bg-white p-3 shadow-2xl"><div className="flex items-center gap-2 border-b border-slate-100 pb-2"><Search className="h-4 w-4 text-slate-400"/><input autoFocus value={query} onChange={event => setQuery(event.target.value)} placeholder="Search started packages…" className="min-w-0 flex-1 bg-transparent text-sm text-slate-800 outline-none placeholder:text-slate-400"/><button onClick={() => setSearchOpen(false)} className="text-xs text-slate-500">Close</button></div><div className="mt-2 max-h-80 overflow-y-auto">{results.length ? results.map(item => <button key={item.id} onClick={() => { window.dispatchEvent(new CustomEvent("writer:eb-open-item", { detail: item.id })); setSearchOpen(false) }} className="flex w-full items-center gap-2 rounded-lg px-2.5 py-2 text-left hover:bg-slate-50"><span className={`h-2 w-2 rounded-full ${item.color}`}/><span className="min-w-0 flex-1 truncate text-xs text-slate-700">{item.title}</span>{item.channel && <span className="rounded bg-emerald-50 px-1.5 py-0.5 text-[9px] font-medium text-emerald-700">{item.channel}</span>}</button>) : <p className="p-4 text-center text-xs text-slate-400">No matching package.</p>}</div></div></div>}
  </aside>{mobilePackagesOpen && <div onClick={event => { if (event.target === event.currentTarget) setMobilePackagesOpen(false) }} className="fixed inset-0 z-[70] flex items-end bg-slate-950/25 p-3 backdrop-blur-[1px] md:hidden"><section className="max-h-[72dvh] w-full overflow-y-auto rounded-2xl border border-slate-200 bg-white p-3 shadow-2xl"><header className="flex items-center justify-between border-b border-slate-100 pb-2"><div><h2 className="text-sm font-bold text-slate-900">Started packages</h2><p className="mt-0.5 text-[10px] text-slate-500">Website drafts and final channel review</p></div><button onClick={() => setMobilePackagesOpen(false)} className="grid h-8 w-8 place-items-center rounded-lg text-slate-500 hover:bg-slate-100" aria-label="Close packages"><X className="h-4 w-4"/></button></header><StartedPackageGroups activeItems={activeItems} websiteItems={websiteItems} reviewItems={reviewItems} hidden=""/></section></div>}</>
}
function MobileButton({ icon: Icon, label, count, onClick }: { icon: typeof LayoutGrid; label: string; count?: number; onClick?: () => void }) { return <button onClick={onClick} className="relative flex min-w-12 flex-col items-center gap-0.5 rounded-lg px-2 py-1 text-[9px] font-medium text-slate-600 hover:bg-slate-200/60"><Icon className="h-4 w-4 text-slate-500"/><span>{label}</span>{count !== undefined && count > 0 && <span className="absolute right-1 top-0 grid h-3.5 min-w-3.5 place-items-center rounded-full bg-indigo-600 px-0.5 text-[8px] font-bold text-white">{count}</span>}</button> }
function StartedPackageGroups({ activeItems, websiteItems, reviewItems, hidden }: { activeItems: Array<{ id: string; title: string; color: string; gate: string; channel?: string }>; websiteItems: Array<{ id: string; title: string; color: string; gate: string; channel?: string }>; reviewItems: Array<{ id: string; title: string; color: string; gate: string; channel?: string }>; hidden: string }) { const allEmpty = !activeItems.length && !websiteItems.length && !reviewItems.length; return <div className="mt-1 space-y-3">{allEmpty ? <p className={`px-2.5 py-1 text-[10px] text-slate-400 ${hidden}`}>No packages yet</p> : <><PackageGroup label="Website articles" hint="fab.careers" tone="amber" items={websiteItems} hidden={hidden}/><PackageGroup label="Final review" hint="by channel" tone="emerald" items={reviewItems} hidden={hidden}/>{activeItems.length > 0 && <PackageGroup label="Other work" hint="brief & adaptation" tone="slate" items={activeItems} hidden={hidden}/>}</>}</div> }
function PackageGroup({ label, hint, tone, items, hidden }: { label: string; hint: string; tone: "amber" | "emerald" | "slate"; items: Array<{ id: string; title: string; color: string; gate: string; channel?: string }>; hidden: string }) { const styles = tone === "amber" ? "bg-amber-50 text-amber-700" : tone === "emerald" ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"; return <section><div className={`mx-2 mb-1 flex items-center justify-between rounded-md px-1.5 py-1 text-[9px] font-semibold ${styles} ${hidden}`}><span>{label}</span><span className="font-medium opacity-70">{items.length ? items.length : hint}</span></div>{items.length ? <div className="space-y-0.5">{items.map(item => <Star key={item.id} {...item} hidden={hidden} hideChannel={tone === "amber"}/>)}</div> : <p className={`px-2.5 py-1 text-[10px] text-slate-400 ${hidden}`}>No {label.toLowerCase()} yet</p>}</section> }
function SideButton({ icon: Icon, label, active, collapsed, count, onClick }: { icon: typeof LayoutGrid; label: string; active?: boolean; collapsed: boolean; count?: number; onClick?: () => void }) { return <button onClick={onClick} title={collapsed ? label : undefined} className={`flex h-8 w-full items-center gap-2.5 rounded-lg px-2.5 text-left text-xs font-medium ${active ? "bg-slate-200/70 text-slate-900 font-semibold" : "text-slate-600 hover:bg-slate-200/50"} ${collapsed ? "justify-center px-0" : ""}`}><Icon className="h-4 w-4 shrink-0 text-slate-500"/><span className={collapsed ? "hidden" : "truncate"}>{label}</span>{count !== undefined && <span className={`ml-auto rounded-md bg-slate-200 px-1.5 py-0.5 text-[10px] font-bold text-slate-600 ${collapsed ? "hidden" : ""}`}>{count}</span>}</button> }
function SectionLabel({ label, hidden }: { label: string; hidden: string }) { return <div className={`flex items-center justify-between px-2.5 pt-2 text-[10px] font-semibold uppercase tracking-wider text-slate-400 ${hidden}`}><span>{label}</span><ChevronDown className="h-3.5 w-3.5"/></div> }
function Star({ id, title, color, hidden, channel, hideChannel }: { id: string; title: string; color: string; hidden: string; channel?: string; hideChannel?: boolean }) { return <div className="group flex h-7 w-full items-center gap-2 rounded-lg px-2.5 text-xs font-medium text-slate-600 hover:bg-slate-200/50"><button onClick={() => window.dispatchEvent(new CustomEvent("writer:eb-open-item", { detail: id }))} className="flex min-w-0 flex-1 items-center gap-2 text-left"><span className={`h-2 w-2 shrink-0 rounded-full ${color}`}/><span className={`min-w-0 flex-1 truncate ${hidden}`}>{title}</span>{channel && !hideChannel && <span className={`rounded bg-emerald-50 px-1 py-0.5 text-[8px] font-semibold text-emerald-700 ${hidden}`}>{channel}</span>}</button><button onClick={event => { event.stopPropagation(); window.dispatchEvent(new CustomEvent("writer:eb-delete", { detail: id })) }} title="Delete item" aria-label={`Delete ${title}`} className={`grid h-5 w-5 place-items-center rounded text-slate-400 hover:bg-red-50 hover:text-red-600 ${hidden} group-hover:grid`}><Trash2 className="h-3 w-3"/></button></div> }
