import { BookOpenCheck, ChevronDown, CircleHelp, Globe2, Inbox, LayoutGrid, Linkedin, NotebookPen, PanelLeftClose, PanelLeftOpen, PlusSquare, Search, Share2 } from "lucide-react"
import { useState } from "react"
import BrandMark from "./BrandMark"
interface Props { onOpenSettings: () => void; onNewPackage: () => void; onOpenDiscovery: () => void }
export default function EbSidebar({ onOpenSettings, onNewPackage, onOpenDiscovery }: Props) {
  const [collapsed, setCollapsed] = useState(false)
  const hidden = collapsed ? "hidden" : ""
  return <aside className={`eb-sidebar hidden h-full shrink-0 flex-col justify-between rounded-2xl border border-slate-200/80 bg-slate-50 shadow-sm transition-[width,padding] duration-250 md:flex ${collapsed ? "w-16 p-2" : "w-64 p-3"}`}>
    <div className="flex flex-col gap-4 overflow-hidden"><div className="flex items-center justify-between rounded-lg px-2 py-1.5 hover:bg-slate-200/60"><button onClick={onNewPackage} className="flex min-w-0 items-center gap-2"><BrandMark className="h-5 w-5"/><span className={`truncate text-xs font-semibold text-slate-800 ${hidden}`}>Writer Studio</span><ChevronDown className={`h-4 w-4 shrink-0 text-slate-400 ${hidden}`}/></button><button onClick={() => setCollapsed(value => !value)} className="rounded p-1 text-slate-400 hover:bg-slate-300/50 hover:text-slate-600" aria-label="Toggle sidebar">{collapsed ? <PanelLeftOpen className="h-4 w-4"/> : <PanelLeftClose className="h-4 w-4"/>}</button></div>
      <nav className="space-y-0.5"><SideButton icon={LayoutGrid} label="EB Packages" active collapsed={collapsed} onClick={onNewPackage}/><SideButton icon={Inbox} label="Discovery Inbox" collapsed={collapsed} count="4" onClick={onOpenDiscovery}/><SideButton icon={BookOpenCheck} label="Knowledge library" collapsed={collapsed} onClick={onOpenSettings}/><SideButton icon={NotebookPen} label="Personas & approvers" collapsed={collapsed} onClick={onOpenSettings}/></nav>
      <SectionLabel label="Starred packages" hidden={hidden}/><div className="space-y-0.5"><Star label="Keep It, Share It, Use It" color="bg-blue-500" hidden={hidden}/><Star label="Customer feedback → visual brief" color="bg-emerald-500" hidden={hidden}/><Star label="Friday sharing habit" color="bg-amber-500" hidden={hidden}/></div>
      <SectionLabel label="Publishing channels" hidden={hidden}/><nav className="space-y-0.5"><SideButton icon={Globe2} label="fab.careers Article" active collapsed={collapsed}/><SideButton icon={Share2} label="Threads & Facebook" collapsed={collapsed}/><SideButton icon={Linkedin} label="LinkedIn" collapsed={collapsed}/></nav>
    </div>
    <div className="flex items-center justify-between border-t border-slate-200 pt-2 text-slate-500"><button className="rounded-lg p-1.5 hover:bg-slate-200/60" aria-label="Help"><CircleHelp className="h-4 w-4"/></button><button onClick={onOpenSettings} className={`rounded-lg p-1.5 hover:bg-slate-200/60 ${hidden}`} aria-label="Settings"><PlusSquare className="h-4 w-4"/></button><button className={`rounded-lg p-1.5 hover:bg-slate-200/60 ${hidden}`} aria-label="Search"><Search className="h-4 w-4"/></button></div>
  </aside>
}
function SideButton({ icon: Icon, label, active, collapsed, count, onClick }: { icon: typeof LayoutGrid; label: string; active?: boolean; collapsed: boolean; count?: string; onClick?: () => void }) { return <button onClick={onClick} title={collapsed ? label : undefined} className={`flex h-8 w-full items-center gap-2.5 rounded-lg px-2.5 text-left text-xs font-medium ${active ? "bg-slate-200/70 text-slate-900 font-semibold" : "text-slate-600 hover:bg-slate-200/50"} ${collapsed ? "justify-center px-0" : ""}`}><Icon className="h-4 w-4 shrink-0 text-slate-500"/><span className={collapsed ? "hidden" : "truncate"}>{label}</span>{count && <span className={`ml-auto rounded-md bg-slate-200 px-1.5 py-0.5 text-[10px] font-bold text-slate-600 ${collapsed ? "hidden" : ""}`}>{count}</span>}</button> }
function SectionLabel({ label, hidden }: { label: string; hidden: string }) { return <div className={`flex items-center justify-between px-2.5 pt-2 text-[10px] font-semibold uppercase tracking-wider text-slate-400 ${hidden}`}><span>{label}</span><ChevronDown className="h-3.5 w-3.5"/></div> }
function Star({ label, color, hidden }: { label: string; color: string; hidden: string }) { return <button className="flex h-7 w-full items-center gap-2 rounded-lg px-2.5 text-left text-xs font-medium text-slate-600 hover:bg-slate-200/50"><span className={`h-2 w-2 shrink-0 rounded-full ${color}`}/><span className={`truncate ${hidden}`}>{label}</span></button> }
