import { AlertTriangle, Bell, Check, CheckCircle2, ChevronDown, FileText, Filter, Grid2X2, Lightbulb, List, LoaderCircle, Paperclip, Play, RotateCcw, Search, Send, Sparkles, Upload, X } from "lucide-react"
import { useEffect, useRef, useState } from "react"
import type { ReactNode } from "react"

type Gate = "brief" | "article" | "adapt" | "review"
type View = "grid" | "list"
type Decision = "done" | "reject" | "recheck" | null
type Task = { id: string; gate: Gate; title: string; status: "ready" | "checking" | "drafting" | "adapting" | "review"; pillar?: string; persona?: string; type?: string; channel?: "Threads" | "Facebook" | "LinkedIn"; decision?: Decision; source?: "input" | "discovery" }

const gateConfig: Record<Gate, { title: string; subtitle: string; tone: "blue" | "amber" | "purple" | "emerald" }> = {
  brief: { title: "Brief · Gate 1", subtitle: "Extract, checklist, pillar & persona", tone: "blue" },
  article: { title: "Website article · Gate 2", subtitle: "fab.careers draft ready for approval", tone: "amber" },
  adapt: { title: "Adapt channel", subtitle: "Threads, Facebook & LinkedIn in progress", tone: "purple" },
  review: { title: "Review · Gate 3", subtitle: "Repetition check & final channel action", tone: "emerald" },
}
const initialTasks: Task[] = [
  { id: "brief-1", gate: "brief", title: "How a Friday sharing habit saves useful context", status: "ready", pillar: "Analytical & Clarity-driven", persona: "L&D Executive", type: "C1 · Learning practice", source: "discovery" },
  { id: "brief-2", gate: "brief", title: "Customer feedback → a one-page visual brief", status: "checking", source: "input" },
  { id: "article-1", gate: "article", title: "Keep It, Share It, Use It", status: "drafting", pillar: "Analytical & Clarity-driven", persona: "AI Engineer", type: "C1 · Learning practice" },
  { id: "adapt-1", gate: "adapt", title: "Keep It, Share It, Use It", status: "adapting", channel: "Threads" },
  { id: "adapt-2", gate: "adapt", title: "Keep It, Share It, Use It", status: "adapting", channel: "Facebook" },
  { id: "adapt-3", gate: "adapt", title: "Keep It, Share It, Use It", status: "adapting", channel: "LinkedIn" },
  { id: "review-1", gate: "review", title: "Learning culture, in the small details", status: "review", channel: "Threads" },
]

export default function EbWorkingSpace() {
  const [view, setView] = useState<View>("grid")
  const [tasks, setTasks] = useState<Task[]>(initialTasks)
  const [input, setInput] = useState("")
  const [fileName, setFileName] = useState("")
  const [filterOpen, setFilterOpen] = useState(false)
  const [discoveryOpen, setDiscoveryOpen] = useState(false)
  const filterRef = useRef<HTMLDivElement>(null)
  const discoveryRef = useRef<HTMLDivElement>(null)
  useEffect(() => { const close = (event: MouseEvent) => { if (!filterRef.current?.contains(event.target as Node)) setFilterOpen(false); if (!discoveryRef.current?.contains(event.target as Node)) setDiscoveryOpen(false) }; document.addEventListener("click", close); return () => document.removeEventListener("click", close) }, [])
  useEffect(() => { const adapting = tasks.filter(task => task.gate === "adapt" && task.status === "adapting"); if (!adapting.length) return; const timer = window.setTimeout(() => setTasks(current => { const completed = current.filter(task => task.gate === "adapt" && task.status === "adapting"); return [...current.filter(task => !(task.gate === "adapt" && task.status === "adapting")), ...completed.map(task => ({ ...task, id: `review-${task.id}`, gate: "review" as Gate, status: "review" as const }))] }), 1500); return () => window.clearTimeout(timer) }, [tasks])
  const createBrief = (title: string, source: "input" | "discovery") => setTasks(current => [...current, { id: `brief-${Date.now()}`, gate: "brief", title, status: "ready", source, pillar: "Analytical & Clarity-driven", persona: "L&D Executive", type: "C1 · Learning practice" }])
  const analyze = () => { if (!input.trim() && !fileName) return; createBrief(input.trim() || `Material from ${fileName}`, "input"); setInput(""); setFileName("") }
  const approveBrief = (task: Task) => setTasks(current => current.map(item => item.id === task.id ? { ...item, gate: "article", status: "drafting" } : item))
  const approveArticle = (task: Task) => setTasks(current => { const next = current.filter(item => item.id !== task.id); const channels: Task["channel"][] = ["Threads", "Facebook", "LinkedIn"]; return [...next, ...channels.map(channel => ({ id: `adapt-${task.id}-${channel}`, gate: "adapt" as Gate, status: "adapting" as const, title: task.title, channel }))] })
  const decide = (id: string, decision: Exclude<Decision, null>) => setTasks(current => current.map(task => task.id === id ? { ...task, decision } : task))
  const gates: Gate[] = ["brief", "article", "adapt", "review"]
  return <main className="eb-workspace continuous-workspace flex min-h-0 flex-1 flex-col overflow-hidden rounded-2xl border border-slate-200/80 bg-white">
    <header className="flex h-12 shrink-0 items-center justify-between border-b border-slate-100 px-4"><div className="flex items-center gap-2 text-xs text-slate-500"><span className="font-semibold text-slate-800">Content Engine</span><span>/</span><span>EB Content Packages</span></div><div className="flex items-center gap-2"><button onClick={() => document.querySelector<HTMLTextAreaElement>("#eb-input")?.focus()} className="inline-flex items-center gap-1.5 rounded-lg bg-indigo-600 px-3 py-1.5 text-xs font-semibold text-white"><Sparkles className="h-3.5 w-3.5"/>Tạo EB package</button><button className="relative grid h-7 w-7 place-items-center rounded-lg bg-slate-100 text-slate-600"><Bell className="h-4 w-4"/><span className="absolute right-1 top-1 h-2 w-2 rounded-full bg-red-500 ring-2 ring-white"/></button></div></header>
    <div className="flex shrink-0 items-center justify-between border-b border-slate-100 px-4 py-2"><div className="flex items-center gap-2"><div ref={filterRef} className="relative"><button onClick={event => { event.stopPropagation(); setFilterOpen(value => !value) }} className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 px-2.5 py-1 text-xs font-semibold text-slate-700"><Filter className="h-3.5 w-3.5"/>Filter<ChevronDown className="h-3.5 w-3.5"/></button>{filterOpen && <div className="absolute left-0 top-[calc(100%+8px)] z-50 w-60 rounded-xl border border-slate-200 bg-white p-1.5 text-xs shadow-xl">{["Pillar", "Persona", "Article type", "Channel", "Gate status"].map(label => <button key={label} className="flex w-full items-center gap-2 rounded-lg px-2.5 py-2 text-left text-slate-600 hover:bg-slate-50"><Search className="h-3.5 w-3.5 text-slate-400"/>{label}</button>)}</div>}</div><span className="rounded-md bg-slate-100 px-2 py-1 text-[10px] text-slate-500">Shell mode · simulated</span></div><div className="flex rounded-lg border border-slate-200 bg-slate-100 p-0.5"><button onClick={() => setView("list")} className={`rounded-md px-2 py-1 ${view === "list" ? "bg-white shadow-2xs" : ""}`}><List className="h-3.5 w-3.5"/></button><button onClick={() => setView("grid")} className={`rounded-md px-2 py-1 ${view === "grid" ? "bg-white shadow-2xs" : ""}`}><Grid2X2 className="h-3.5 w-3.5"/></button></div></div>
    <section className="min-h-0 flex-1 overflow-y-auto bg-slate-50/30 p-3"><div className={view === "grid" ? "grid items-start gap-3 xl:grid-cols-4" : "space-y-4"}>{gates.map(gate => <GateGroup key={gate} gate={gate} tasks={tasks.filter(task => task.gate === gate)} view={view} onBrief={approveBrief} onArticle={approveArticle} onDecision={decide}/>)}</div></section>
    <div className="shrink-0 bg-gradient-to-t from-slate-50 via-slate-50 to-transparent px-3 pb-3 pt-7"><div className="glow-input-container mx-auto max-w-4xl rounded-xl p-px"><div className="rounded-[11px] bg-white p-2 shadow-sm"><div className="flex gap-2"><Sparkles className="mt-1 h-4 w-4 shrink-0 text-indigo-600"/><textarea id="eb-input" value={input} onChange={event => setInput(event.target.value)} rows={2} placeholder="Nhập một khoảnh khắc, ý tưởng hoặc câu chuyện thật từ F.Learning…" className="min-h-12 flex-1 resize-none bg-transparent text-sm text-slate-800 outline-none placeholder:text-slate-400"/><label className="grid h-8 w-8 cursor-pointer place-items-center self-end rounded-lg border border-slate-200 text-slate-500 hover:bg-slate-50" title="Upload material"><Upload className="h-3.5 w-3.5"/><input type="file" className="hidden" onChange={event => setFileName(event.target.files?.[0]?.name ?? "")}/></label><button disabled={!input.trim() && !fileName} onClick={analyze} className="self-end inline-flex items-center gap-1.5 rounded-lg bg-indigo-600 px-2.5 py-1.5 text-xs font-semibold text-white disabled:opacity-40"><Send className="h-3.5 w-3.5"/>Analyze</button></div>{fileName && <p className="mt-1 flex items-center gap-1 text-[10px] text-slate-500"><Paperclip className="h-3 w-3"/>{fileName}</p>}<div className="mt-1.5 flex flex-wrap gap-1.5 border-t border-slate-200/80 pt-2"><div ref={discoveryRef} className="relative"><button onClick={event => { event.stopPropagation(); setDiscoveryOpen(value => !value) }} className="rounded-md bg-slate-50 px-2 py-1 text-[10px] font-medium text-slate-500 hover:bg-slate-100">Discovery Mode</button>{discoveryOpen && <Discovery onPick={title => { createBrief(title, "discovery"); setDiscoveryOpen(false) }}/>}</div><span className="px-1 py-1 text-[10px] text-slate-400">Scans configured sources; suggestions are never auto-approved.</span></div></div></div></div>
  </main>
}

function GateGroup({ gate, tasks, view, onBrief, onArticle, onDecision }: { gate: Gate; tasks: Task[]; view: View; onBrief: (task: Task) => void; onArticle: (task: Task) => void; onDecision: (id: string, decision: Exclude<Decision, null>) => void }) { const config = gateConfig[gate]; return <section className={view === "grid" ? `gate-column gate-${config.tone} rounded-2xl border p-3` : ""}><div className="mb-3 flex items-center justify-between"><div><div className="flex items-center gap-1.5"><span className={`gate-dot gate-dot-${config.tone}`}><Check className="h-2.5 w-2.5"/></span><h2 className="text-xs font-bold text-slate-800">{config.title}</h2></div><p className="mt-1 text-[10px] text-slate-500">{config.subtitle}</p></div><span className="text-xs text-slate-400">{tasks.length}</span></div><div className="space-y-2">{tasks.map(task => <TaskCard key={task.id} task={task} view={view} onBrief={onBrief} onArticle={onArticle} onDecision={onDecision}/>) || <p className="py-5 text-center text-[10px] text-slate-400">No tasks</p>}</div></section> }
function TaskCard({ task, view, onBrief, onArticle, onDecision }: { task: Task; view: View; onBrief: (task: Task) => void; onArticle: (task: Task) => void; onDecision: (id: string, decision: Exclude<Decision, null>) => void }) { const isWorking = ["checking", "drafting", "adapting"].includes(task.status); return <article className={`rounded-xl border border-slate-200/80 bg-white p-3 shadow-2xs ${view === "list" ? "flex items-center justify-between gap-4" : ""}`}><div className="min-w-0"><div className="flex flex-wrap gap-1">{task.channel && <Tag>{task.channel}</Tag>}{task.type && <Tag>{task.type}</Tag>}{task.source === "discovery" && <Tag>Discovery suggestion</Tag>}{isWorking && <span className="inline-flex items-center gap-1 rounded-md bg-amber-50 px-1.5 py-0.5 text-[10px] font-semibold text-amber-600"><LoaderCircle className="h-3 w-3 animate-spin"/>{task.status === "adapting" ? "Adapting" : task.status === "drafting" ? "Drafting" : "Extract & check"}</span>}</div><h3 className="mt-2 text-xs font-bold leading-snug text-slate-900">{task.title}</h3>{task.gate === "brief" && <p className="mt-1 text-[10px] text-slate-500">Pillar: {task.pillar ?? "awaiting input"} · Persona: {task.persona ?? "awaiting mapping"}</p>}{task.gate === "review" && <p className="mt-1 text-[10px] text-slate-500">Repetition check: clear of last C1 format.</p>}</div><div className={`mt-3 flex flex-wrap gap-1.5 ${view === "list" ? "mt-0 shrink-0" : ""}`}>{task.gate === "brief" && task.status !== "checking" && <button onClick={() => onBrief(task)} className="rounded-lg bg-indigo-600 px-2 py-1 text-[10px] font-semibold text-white">Approve brief</button>}{task.gate === "article" && <button onClick={() => onArticle(task)} className="rounded-lg bg-indigo-600 px-2 py-1 text-[10px] font-semibold text-white">Approve article</button>}{task.gate === "review" && !task.decision && <><button onClick={() => onDecision(task.id, "done")} className="rounded-lg bg-emerald-500 px-2 py-1 text-[10px] font-semibold text-white">Done</button><button onClick={() => onDecision(task.id, "recheck")} className="rounded-lg bg-amber-50 px-2 py-1 text-[10px] font-semibold text-amber-600">Re-check</button><button onClick={() => onDecision(task.id, "reject")} className="rounded-lg bg-red-50 px-2 py-1 text-[10px] font-semibold text-red-600">Reject</button></>}{task.decision && <Tag>{task.decision}</Tag>}</div></article> }
function Discovery({ onPick }: { onPick: (title: string) => void }) { const ideas = ["Why young creatives value a team that explains the why", "A small habit that makes feedback easier to use", "When an informal sharing session becomes a learning system"]; return <div className="absolute bottom-[calc(100%+8px)] left-0 z-50 w-80 rounded-xl border border-purple-200 bg-white p-2 shadow-xl"><div className="flex items-center gap-2 border-b border-slate-100 px-2 py-1.5"><Lightbulb className="h-3.5 w-3.5 text-purple-600"/><p className="text-xs font-semibold text-slate-800">Discovery suggestions</p></div><p className="px-2 pt-2 text-[10px] text-slate-500">Simulated scan: channel rules + pillar library. Choose an idea to run Gate 1.</p>{ideas.map((idea, index) => <button key={idea} onClick={() => onPick(idea)} className="mt-1 w-full rounded-lg px-2 py-2 text-left text-xs text-slate-700 hover:bg-purple-50"><span className="mr-1.5 text-purple-500">{index + 1}.</span>{idea}</button>)}</div> }
function Tag({ children }: { children: ReactNode }) { return <span className="rounded-md bg-slate-100 px-1.5 py-0.5 text-[9px] font-medium text-slate-500">{children}</span> }
