import { AlertTriangle, ArrowLeft, ArrowRight, Ban, Bell, Check, CheckCircle2, ChevronDown, ClipboardCheck, Edit3, FileText, Filter, Grid2X2, Lightbulb, List, LoaderCircle, MoreHorizontal, Play, Plus, Send, SlidersHorizontal, Sparkles, X } from "lucide-react"
import { useEffect, useRef, useState } from "react"
import type { ReactNode } from "react"

type View = "grid" | "list"
type PackageStage = 0 | 1 | 2 | 3
type Run = { title: string; state: string; pillar: string; gate: string; channel: string }
const runs: Run[] = [
  { title: "How a Friday sharing habit saves useful context", state: "discovery", pillar: "Analytical", gate: "Idea", channel: "fab.careers" },
  { title: "A clearer way to turn client feedback into a brief", state: "progress", pillar: "Ownership", gate: "Step 1", channel: "fab.careers" },
  { title: "Keep It, Share It, Use It", state: "review", pillar: "Analytical", gate: "Gate 2", channel: "LinkedIn" },
  { title: "Learning culture, in the small details", state: "done", pillar: "Energetic", gate: "Published", channel: "Facebook" },
] as const
const columns = [
  { key: "review", title: "In review", helper: "Waiting for a gate", icon: LoaderCircle, tone: "blue" },
  { key: "progress", title: "In progress", helper: "Step 0–1", icon: Play, tone: "amber" },
  { key: "discovery", title: "Discovery", helper: "AI ideas not selected", icon: Lightbulb, tone: "purple" },
  { key: "done", title: "Done", helper: "Published & logged", icon: Check, tone: "emerald" },
] as const

export default function EbWorkingSpace() {
  const [view, setView] = useState<View>("grid")
  const [raw, setRaw] = useState("")
  const [screen, setScreen] = useState<"board" | "package">("board")
  const [stage, setStage] = useState<PackageStage>(0)
  const [filterOpen, setFilterOpen] = useState(false)
  const [noticeOpen, setNoticeOpen] = useState(false)
  const filtersRef = useRef<HTMLDivElement>(null)
  const noticeRef = useRef<HTMLDivElement>(null)
  const hasInput = raw.trim().length > 12
  useEffect(() => {
    const closePopovers = (event: MouseEvent) => {
      if (!filtersRef.current?.contains(event.target as Node)) setFilterOpen(false)
      if (!noticeRef.current?.contains(event.target as Node)) setNoticeOpen(false)
    }
    document.addEventListener("click", closePopovers)
    return () => document.removeEventListener("click", closePopovers)
  }, [])
  const openPackage = (nextStage: PackageStage = 0) => { setStage(nextStage); setScreen("package") }
  return <main className="eb-workspace continuous-workspace flex min-h-0 flex-1 flex-col overflow-hidden rounded-2xl border border-slate-200/80 bg-white">
    <header className="flex h-12 shrink-0 items-center justify-between border-b border-slate-100 px-4"><div className="flex items-center gap-2 text-xs font-medium text-slate-500"><button onClick={() => screen === "package" ? setScreen("board") : undefined} className="hover:text-slate-800"><ArrowLeft className="h-4 w-4"/></button><button className="hover:text-slate-800"><ArrowRight className="h-4 w-4"/></button><span className="ml-1 font-semibold text-slate-800">Content Engine</span><span>/</span><span className="text-slate-700">{screen === "package" ? "EB Content Package" : "All Drafts & Tasks"}</span><MoreHorizontal className="h-4 w-4"/></div><div className="flex items-center gap-2"><button onClick={() => screen === "package" ? setStage(0) : document.querySelector<HTMLTextAreaElement>("#eb-ai-input")?.focus()} className="inline-flex items-center gap-1.5 rounded-lg bg-indigo-600 px-3 py-1.5 text-xs font-semibold text-white shadow-sm hover:bg-indigo-700"><Sparkles className="h-3.5 w-3.5"/>{screen === "package" ? "New package" : "Tạo bài mới"}</button><div ref={noticeRef} className="relative"><button onClick={(event) => { event.stopPropagation(); setNoticeOpen(value => !value) }} className="relative grid h-7 w-7 place-items-center rounded-lg bg-slate-100 text-slate-600 hover:bg-slate-200" aria-label="Notifications"><Bell className="h-4 w-4"/><span className="absolute right-1 top-1 h-2 w-2 rounded-full bg-red-500 ring-2 ring-white"/></button>{noticeOpen && <div role="status" className="absolute right-0 top-[calc(100%+8px)] z-50 w-80 rounded-2xl border border-slate-200/90 bg-white p-3.5 text-xs text-slate-500 shadow-xl"><p className="font-semibold text-slate-800">EB Skill is ready for review</p><p className="mt-1">Shell mode is active. No Supabase data is connected.</p></div>}</div></div></header>
    <div className="flex shrink-0 items-center justify-between border-b border-slate-100 bg-white px-4 py-3"><div className="flex items-center gap-2"><div ref={filtersRef} className="relative"><button onClick={(event) => { event.stopPropagation(); setFilterOpen(value => !value) }} className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 px-2.5 py-1 text-xs font-semibold text-slate-700 hover:bg-slate-50"><SlidersHorizontal className="h-3.5 w-3.5"/>Filter</button>{filterOpen && <div className="absolute left-0 top-[calc(100%+8px)] z-50 w-64 rounded-xl border border-slate-200 bg-white p-1.5 text-xs shadow-xl"><div className="flex items-center gap-2 border-b border-slate-100 px-2 py-1.5 text-slate-400"><Filter className="h-3.5 w-3.5"/><span>Filter by pillar, persona or gate…</span></div>{["Status gate", "Persona / Target Audience", "Article type & Channel", "Pillar & Tone", "Blocked / evidence"].map(item => <button key={item} className="flex w-full items-center gap-2 rounded-lg px-2.5 py-2 text-left text-slate-600 hover:bg-slate-100"><Filter className="h-3.5 w-3.5 text-slate-400"/>{item}</button>)}</div>}</div><div className="flex -space-x-1.5"><Avatar initials="MA"/><Avatar initials="HM"/><Avatar initials="MR"/><Avatar initials="AO"/></div><FilterChip prefix="Platform is" label="Blog & SEO"/><FilterChip prefix="Tone:" label="Professional, Expert"/></div><div className="flex rounded-lg border border-slate-200 bg-slate-100 p-0.5"><button onClick={() => setView("list")} className={`inline-flex items-center gap-1.5 rounded-md px-2.5 py-1 text-xs font-semibold ${view === "list" ? "bg-white text-slate-800 shadow-2xs" : "text-slate-500"}`}><List className="h-3.5 w-3.5 text-indigo-600"/><span className="hidden sm:inline">List View</span></button><button onClick={() => setView("grid")} className={`inline-flex items-center gap-1.5 rounded-md px-2.5 py-1 text-xs font-semibold ${view === "grid" ? "bg-white text-slate-800 shadow-2xs" : "text-slate-500"}`}><Grid2X2 className="h-3.5 w-3.5"/><span className="hidden sm:inline">Grid Card</span></button></div></div>
    {screen === "package" ? <PackageFlow stage={stage} onStage={setStage} onBack={() => setScreen("board")}/> : <><section className="min-h-0 flex-1 overflow-y-auto bg-slate-50/30 p-3"><div className="mx-auto max-w-none pb-36">{view === "grid" ? <DemoGrid onOpen={openPackage}/> : <div className="space-y-6"><ListGroup title="In review / Generated Drafts" tone="blue" runs={[runs[2], { ...runs[2], title: "Build a workplace story from useful team habits", gate: "Gate 1" }, { ...runs[2], title: "A culture claim needs stronger source evidence", gate: "Blocked" }]}/><ListGroup title="In progress / AI Processing" tone="amber" runs={[runs[1]]}/><ListGroup title="Backlog / AI Auto-Crawled Ideas" tone="purple" runs={[runs[0]]}/><ListGroup title="Done / Published" tone="emerald" runs={[runs[3]]}/></div>}</div></section><div className="sticky bottom-0 shrink-0 bg-gradient-to-t from-slate-50 via-slate-50 to-transparent px-3 pb-3 pt-8 md:px-4"><div className="glow-input-container mx-auto max-w-4xl rounded-xl p-px"><div className="rounded-[11px] bg-white p-2 shadow-sm"><div className="flex gap-2"><Sparkles className="mt-1 h-4 w-4 shrink-0 text-indigo-600"/><textarea id="eb-ai-input" value={raw} onChange={event => setRaw(event.target.value)} rows={2} placeholder="Dán một khoảnh khắc, ghi chú sự kiện hoặc câu chuyện từ team…" className="min-h-12 flex-1 resize-none bg-transparent text-sm leading-5 text-slate-800 outline-none placeholder:text-slate-400"/><button disabled={!hasInput} onClick={() => openPackage(0)} className="self-end inline-flex items-center gap-1.5 rounded-lg bg-indigo-600 px-2.5 py-1.5 text-xs font-semibold text-white disabled:opacity-40"><Send className="h-3.5 w-3.5"/>Analyze</button></div><div className="mt-1.5 flex flex-wrap gap-1.5 border-t border-slate-200/80 pt-2">{["Tạo bài viết mới", "Gợi ý chủ đề", "Xem log chống lặp", "Tìm xu hướng hot"].map((action, index) => <button key={action} onClick={() => index === 0 && document.querySelector<HTMLTextAreaElement>("#eb-ai-input")?.focus()} className="rounded-md bg-slate-50 px-2 py-1 text-[10px] font-medium text-slate-500 hover:bg-slate-100">{action}</button>)}</div></div></div></div></>}
  </main>
}
function KanbanColumn({ title, helper, icon: Icon, tone, run }: Omit<typeof columns[number], "key"> & { run: Run }) { return <section className={`kanban-column kanban-${tone} min-h-52 rounded-2xl border p-3 shadow-2xs`}><div className="flex items-center justify-between px-1"><div className="flex items-center gap-1.5"><span className="grid h-3.5 w-3.5 place-items-center rounded-full text-white"><Icon className={`h-2.5 w-2.5 ${tone === "blue" ? "animate-spin" : ""}`}/></span><h2 className="text-xs font-bold text-slate-800">{title}</h2></div><span className="text-xs text-slate-400">1</span></div><p className="mt-1 px-1 text-[10px] text-slate-500">{helper}</p><div className="mt-3"><RunCard run={run}/></div></section> }
function DemoGrid({ onOpen }: { onOpen: (stage: PackageStage) => void }) { return <div className="grid items-start gap-4 lg:grid-cols-4"><DemoColumn tone="blue" title="In review / Generated" count="3" icon="review"><DemoCard onClick={() => onOpen(1)} badge="Brief review" badgeTone="indigo" meta="Gate 1" title="Learning habits people actually want to share"/><DemoCard onClick={() => onOpen(2)} badge="Article review" badgeTone="emerald" title="Keep It, Share It, Use It"/><DemoCard onClick={() => onOpen(1)} badge="Blocked tone" badgeTone="red" title="Culture claim needs supporting evidence"/></DemoColumn><DemoColumn tone="amber" title="In progress / AI Process" count="1" icon="progress"><DemoCard onClick={() => onOpen(0)} badge="Input check 65%" badgeTone="amber" title="A clearer way to turn client feedback into a brief" detail="Đang kiểm tra evidence & gaps…"/></DemoColumn><DemoColumn tone="purple" title="Backlog / AI Crawled" count="1" icon="backlog"><DemoCard onClick={() => onOpen(0)} badge="Discovery idea" badgeTone="slate" title="How a Friday sharing habit saves useful context"/></DemoColumn><DemoColumn tone="emerald" title="Done / Published" count="1" icon="done"><DemoCard onClick={() => onOpen(3)} badge="Published" badgeTone="emerald" title="Learning culture, in the small details" done/></DemoColumn></div> }
function DemoColumn({ tone, title, count, icon, children }: { tone: "blue" | "amber" | "purple" | "emerald"; title: string; count: string; icon: "review" | "progress" | "backlog" | "done"; children: ReactNode }) { const Icon = icon === "review" ? LoaderCircle : icon === "progress" ? Play : icon === "done" ? Check : Lightbulb; return <section className={`demo-column demo-column-${tone} rounded-2xl border p-3 shadow-2xs`}><div className="flex items-center justify-between px-0.5"><div className="flex items-center gap-1.5"><span className={`demo-column-icon demo-column-icon-${tone} grid h-3.5 w-3.5 place-items-center rounded-full text-white`}><Icon className={`h-2.5 w-2.5 ${icon === "review" ? "animate-spin" : ""}`}/></span><h2 className="text-xs font-bold text-slate-800">{title}</h2></div><span className="text-xs font-medium text-slate-400">{count}</span></div><div className="mt-3 space-y-3">{children}</div></section> }
function DemoCard({ badge, badgeTone, meta, title, detail, done, onClick }: { badge: string; badgeTone: "indigo" | "emerald" | "red" | "amber" | "slate"; meta?: string; title: string; detail?: string; done?: boolean; onClick?: () => void }) { const badgeClasses = { indigo: "bg-indigo-50 text-indigo-600", emerald: "bg-emerald-50 text-emerald-600", red: "bg-red-50 text-red-600", amber: "bg-amber-100 text-amber-700", slate: "bg-slate-100 text-slate-500" }[badgeTone]; return <button onClick={onClick} className={`block w-full rounded-xl border border-slate-200/80 bg-white p-3 text-left shadow-2xs ${done ? "opacity-80" : "hover:shadow-md"}`}><div className="flex items-center justify-between gap-2"><span className={`rounded-md px-2 py-0.5 text-[10px] font-semibold ${badgeClasses}`}>{badge}</span>{meta && <span className="rounded-md bg-slate-100 px-1.5 py-0.5 text-[10px] font-medium text-slate-500">{meta}</span>}</div><h3 className={`mt-2 text-xs font-bold leading-snug ${done ? "text-slate-500 line-through" : "text-slate-900"}`}>{title}</h3>{detail && <p className="mt-2 text-[11px] text-slate-500">{detail}</p>}</button> }
function PackageFlow({ stage, onStage, onBack }: { stage: PackageStage; onStage: (stage: PackageStage) => void; onBack: () => void }) { const title = ["Input checklist", "Gate 1 — Brief", "Gate 2 — fab.careers article", "Gate 3 — Social package"][stage]; return <section className="min-h-0 flex-1 overflow-y-auto bg-slate-50/30 p-4"><div className="mx-auto max-w-5xl"><div className="mb-4 flex items-center justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">EB Content Package</p><h1 className="mt-1 text-sm font-bold text-slate-900">Keep It, Share It, Use It</h1></div><button onClick={onBack} className="rounded-lg border border-slate-200 px-2.5 py-1.5 text-xs font-medium text-slate-600 hover:bg-slate-50">Back to packages</button></div><StageIndicator stage={stage}/><div className="mt-4 grid gap-4 lg:grid-cols-[minmax(0,1fr)_220px]"><div className="rounded-2xl border border-slate-200/80 bg-white p-4 shadow-2xs"><h2 className="text-xs font-bold text-slate-800">{title}</h2>{stage === 0 ? <Checklist onContinue={() => onStage(1)}/> : <ApprovalContent stage={stage}/>}</div><EvidencePanel/></div>{stage > 0 && <ApprovalActions stage={stage} onApprove={() => onStage(Math.min(3, stage + 1) as PackageStage)}/>}</div></section> }
function StageIndicator({ stage }: { stage: PackageStage }) { return <div className="flex items-center gap-2 text-[10px] font-medium text-slate-400">{["Input", "Brief", "Article", "Social & log"].map((label, index) => <div key={label} className="flex items-center gap-2"><span className={`grid h-5 w-5 place-items-center rounded-full text-[9px] font-bold ${index < stage ? "bg-emerald-500 text-white" : index === stage ? "bg-indigo-600 text-white" : "bg-slate-100 text-slate-400"}`}>{index < stage ? <Check className="h-3 w-3"/> : index}</span><span>{label}</span>{index < 3 && <span className="h-px w-5 bg-slate-200"/>}</div>)}</div> }
function Checklist({ onContinue }: { onContinue: () => void }) { const checks = [[Check, "Theme and workplace moment are present", "text-emerald-600"], [Check, "Named person and F. context are present", "text-emerald-600"], [AlertTriangle, "A direct quote is optional — mark N/A if unavailable", "text-amber-600"], [Ban, "Hiring role / image are still missing", "text-red-600"]] as const; return <div className="mt-4 space-y-3">{checks.map(([Icon, text, color]) => <div key={text} className="flex items-center gap-2 text-xs text-slate-600"><Icon className={`h-4 w-4 ${color}`}/>{text}</div>)}<div className="mt-4 rounded-xl bg-slate-50 p-3"><label className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">Missing information</label><div className="mt-2 flex gap-2"><input className="h-8 flex-1 rounded-lg border border-slate-200 px-2 text-xs" placeholder="Add a detail or note N/A"/><button className="rounded-lg border border-slate-200 px-2 text-[10px] font-semibold text-slate-500">N/A</button></div></div><button onClick={onContinue} className="mt-2 inline-flex items-center gap-1.5 rounded-lg bg-indigo-600 px-3 py-1.5 text-xs font-semibold text-white"><ClipboardCheck className="h-3.5 w-3.5"/>Create brief</button></div> }
function ApprovalContent({ stage }: { stage: PackageStage }) { const text = stage === 1 ? "Primary pillar: Analytical & Clarity-driven. Persona: L&D Executive. Article type: C1 Learning Practice. The brief uses only the source details listed in Evidence." : stage === 2 ? "# Keep It, Share It, Use It\n\nA useful idea is rarely left in one person's notebook. At F.Learning, a practical discovery becomes something the next person can use." : "Threads VN · 2 variants\nFacebook · reflective, no hiring CTA\nLinkedIn EN · credibility-led, MOFU\n\nRepetition check: clear of recent C1 pattern."; return <div className="mt-4 whitespace-pre-line rounded-xl bg-slate-50 p-3 text-xs leading-6 text-slate-700">{text}</div> }
function EvidencePanel() { return <aside className="h-fit rounded-2xl border border-slate-200/80 bg-white p-3 shadow-2xs"><h2 className="text-xs font-bold text-slate-800">Evidence</h2><p className="mt-1 text-[10px] leading-4 text-slate-500">Every claim remains traceable. N/A is never filled by AI.</p><div className="mt-3 space-y-2 text-[10px]"><p className="rounded-lg bg-emerald-50 px-2 py-1.5 text-emerald-700">Raw input · Friday sharing session</p><p className="rounded-lg bg-emerald-50 px-2 py-1.5 text-emerald-700">User answer · client feedback → visual brief</p><p className="rounded-lg bg-amber-50 px-2 py-1.5 text-amber-700">Gap · direct quote marked N/A</p></div></aside> }
function ApprovalActions({ stage, onApprove }: { stage: PackageStage; onApprove: () => void }) { return <div className="mt-4 flex flex-wrap justify-end gap-2"><button className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-medium text-slate-600"><Edit3 className="h-3.5 w-3.5"/>Sửa trực tiếp</button><button className="inline-flex items-center gap-1.5 rounded-lg border border-red-200 bg-red-50 px-3 py-1.5 text-xs font-medium text-red-600"><Ban className="h-3.5 w-3.5"/>Phản biện</button><button onClick={onApprove} className="inline-flex items-center gap-1.5 rounded-lg bg-emerald-500 px-3 py-1.5 text-xs font-semibold text-white"><CheckCircle2 className="h-3.5 w-3.5"/>{stage === 3 ? "Approve & add to log" : "Duyệt gate"}</button></div> }
function RunCard({ run }: { run: Run }) { return <button className="w-full rounded-xl border border-slate-200/80 bg-white p-2.5 text-left shadow-2xs transition hover:shadow-md"><div className="flex items-start gap-2"><div className="grid h-5 w-5 shrink-0 place-items-center rounded-full bg-indigo-600 text-[9px] font-bold text-white">CH</div><span className="line-clamp-2 text-xs font-semibold leading-5 text-slate-800">{run.title}</span></div><div className="mt-2 flex flex-wrap gap-1"><PillarBadge pillar={run.pillar}/><span className="rounded-md bg-slate-100 px-1.5 py-0.5 text-[9px] font-semibold text-slate-500">{run.channel}</span><GateBadge label={run.gate}/></div></button> }
function RunRow({ run }: { run: Run }) { return <button className="flex w-full items-center justify-between rounded-xl border border-slate-200/80 bg-white p-2.5 text-left shadow-2xs transition hover:border-slate-300 hover:shadow-md"><div className="flex items-center gap-3"><CheckCircle2 className="h-4 w-4 text-indigo-600"/><span className="text-xs font-semibold text-slate-800">{run.title}</span></div><div className="flex items-center gap-1.5"><PillarBadge pillar={run.pillar}/><GateBadge label={run.gate}/></div></button> }
function ListGroup({ title, tone, runs: groupRuns }: { title: string; tone: "blue" | "amber" | "purple" | "emerald"; runs: Run[] }) { const Icon = tone === "amber" ? Play : tone === "emerald" ? Check : tone === "purple" ? Lightbulb : LoaderCircle; return <section><div className="mb-2 flex items-center gap-2"><span className={`list-status list-status-${tone} grid h-4 w-4 place-items-center rounded-full text-white`}><Icon className={`h-2.5 w-2.5 ${tone === "blue" ? "animate-spin" : ""}`}/></span><h2 className="text-xs font-semibold text-slate-700">{title}</h2><span className="text-xs font-medium text-slate-400">{groupRuns.length}</span><Plus className="ml-1 h-3.5 w-3.5 text-slate-400"/></div><div className="space-y-1.5 pl-6">{groupRuns.map(run => <RunRow key={run.title} run={run}/>)}</div></section> }
function FilterChip({ prefix, label }: { prefix: string; label: string }) { return <span className="hidden items-center gap-1.5 rounded-md bg-slate-100 px-2.5 py-1 text-xs font-medium text-slate-700 sm:flex"><span className="text-slate-400">{prefix}</span><span className="font-semibold text-indigo-600">{label}</span><X className="h-3 w-3 text-slate-400"/></span> }
function PillarBadge({ pillar }: { pillar: string }) { const colors = pillar === "Analytical" ? "bg-indigo-50 text-indigo-600" : pillar === "Energetic" ? "bg-amber-50 text-amber-600" : "bg-emerald-50 text-emerald-600"; return <span className={`rounded-md px-1.5 py-0.5 text-[9px] font-semibold ${colors}`}>{pillar}</span> }
function GateBadge({ label }: { label: string }) { const colors = label === "Gate 2" ? "bg-amber-50 text-amber-600" : label === "Published" ? "bg-emerald-50 text-emerald-600" : label === "Idea" ? "bg-purple-50 text-purple-600" : "bg-blue-50 text-blue-600"; return <span className={`rounded-md px-1.5 py-0.5 text-[9px] font-semibold ${colors}`}>{label}</span> }
function Avatar({ initials }: { initials: string }) { return <div className="grid h-5 w-5 place-items-center rounded-full border border-white bg-indigo-600 text-[9px] font-bold text-white">{initials}</div> }
